

server:
  port: 8080
# database
spring:
  datasource:
    url: jdbc:mysql://15.164.183.16:3306/ycjh?serverTimezone=UTC
    username: ycjh
    password: 111111
    dirver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  type-aliases-package: com.ycjh.mybatis.mapper
  mapper-locations: mybatis/mapper/**/*.xml

log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator