

SHOW TABLES;

#CODE
DROP TABLE TB_CODE;
CREATE TABLE TB_CODE(
	CODE_ID	VARCHAR(5)	NOT NULL
	,CODE_LABEL	VARCHAR(20)	NOT NULL
	,CDOE_DETAIL	VARCHAR(100)	NULL
	,CODE_ALIAS	VARCHAR(5)	NULL
	,ORDER_RANK	VARCHAR(3)	NOT NULL
	,USE_YN	VARCHAR(2)	NOT NULL
	,REG_DATE	VARCHAR(14)	NOT NULL
	,UPT_DATE	VARCHAR(14)	NULL
    ,PRIMARY KEY (CODE_ID)
)ENGINE INNODB;


#USER
DROP TABLE TB_USER;
CREATE TABLE TB_USER(
    USER_ID VARCHAR(20) NOT NULL
	,USER_NANE	VARCHAR(100)	NOT NULL
	,USER_PWD	VARCHAR(100)	NOT NULL
	,USER_PHONENUM	VARCHAR(100)	NOT NULL
	,USER_EMAIL	VARCHAR(100)	NOT NULL
	,USER_PROFILE	TEXT	NULL
	,USER_TYPE	VARCHAR(5)	NOT NULL
	,REG_DATE	VARCHAR(14)	NOT NULL
	,UPT_DATE	VARCHAR(14)	NULL
	,TEAM_ID	VARCHAR(20)	NOT NULL
    ,PRIMARY KEY (USER_ID)
    ,CONSTRAINT TB_USER_USER_TYPE_FK FOREIGN KEY (USER_TYPE) REFERENCES TB_CODE(CODE_ID) ON UPDATE CASCADE
)ENGINE INNODB;

#ADMIN
DROP TABLE TB_ADMIN;
CREATE TABLE TB_ADMIN(
	ADMIN_ID VARCHAR(20) NOT NULL
	,ADMIN_TYPE	VARCHAR(5)	NOT NULL
	,REG_DATE	VARCHAR(14)	NOT NULL
	,UPT_DATE	VARCHAR(14)	NULL
	,PRIMARY KEY (ADMIN_ID)
    ,CONSTRAINT TB_ADMIN_USER_ID_FK FOREIGN KEY (ADMIN_ID) REFERENCES TB_USER(USER_ID) ON UPDATE CASCADE
    ,CONSTRAINT TB_ADMIN_ADMIN_TYPE_FK FOREIGN KEY (ADMIN_TYPE) REFERENCES TB_CODE(CODE_ID) ON UPDATE CASCADE
)ENGINE INNODB;

#TEAM
DROP TABLE TB_TEAM;
CREATE TABLE TB_TEAM(
	TEAM_ID	VARCHAR(20)	NOT NULL
	,TEAM_NAME	VARCHAR(20)	NOT NULL
	,TEAM_LEADER	VARCHAR(20)	NOT NULL
	,TEAM_PROFILE	TEXT	NULL
	,TEAM_TYPE	VARCHAR(5)	NOT NULL
	,REG_DATE	VARCHAR(14)	NOT NULL
	,UPT_DATE	VARCHAR(14)	NULL
	,PRIMARY KEY (TEAM_ID)
    ,CONSTRAINT TB_TEAM_TEAM_TYPE_FK FOREIGN KEY (TEAM_TYPE) REFERENCES TB_CODE(CODE_ID) ON UPDATE CASCADE
);

#FILE
DROP TABLE TB_FILE;
CREATE TABLE TB_FILE(
	FILE_ID	VARCHAR(20)	NOT NULL
	,FILE_NAME	VARCHAR(100)	NOT NULL
	,FIEL_BASEDIR	VARCHAR(255)	NULL
	,FILE_DIR	VARCHAR(255)	NOT NULL
	,FILE_SIZE	INT	NOT NULL
	,FILE_DESC	TEXT	NULL
	,FILE_IMPORTANT	VARCHAR(2)	NULL
	,FILE_VERSION	VARCHAR(10)	NOT NULL
	,FILE_TYPE	VARCHAR(5)	NOT NULL
	,REG_DATE	VARCHAR(14)	NOT NULL
	,UPT_DATE	VARCHAR(14)	NULL
	,USER_ID	VARCHAR(20)	NOT NULL
	,TEAM_ID	VARCHAR(20)	NOT NULL
	,PRIMARY KEY (FILE_ID)
    ,CONSTRAINT TB_FILE_FILE_TYPE_FK FOREIGN KEY (FILE_TYPE) REFERENCES TB_CODE(CODE_ID) ON UPDATE CASCADE
    ,CONSTRAINT TB_FILE_TEAM_ID_FK FOREIGN KEY (TEAM_ID) REFERENCES TB_TEAM(TEAM_ID) ON UPDATE CASCADE
    ,CONSTRAINT TB_FILE_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_ID) ON UPDATE CASCADE
)







